pastebin/controllers/index.py
from flask import Blueprint, render_template, redirect, url_for, request, session
from flask_security import login_required, current_user
from pastebin.forms.profile import EditProfileForm
from pastebin.models.models import Pastes, User
from pastebin.models import db
import uuid, datetime
from pastebin.forms.pastes import PastesForm, PastesFormGet, getLifeTime

IndexBlueprint = Blueprint('Index', __name__, url_prefix='')


def last_pasts():
    """
    :return: List of resent posts
    """
    timenow = datetime.datetime.now()
    query = db.session.query(Pastes).filter(Pastes.private == False, Pastes.date_timelive > timenow).order_by(
        Pastes.id.desc()).limit(10)
    return query


class IndexView(object):
    @staticmethod
    @IndexBlueprint.route('/', methods=['GET', 'POST'])
    @login_required
    def index():
        form = PastesForm()
        if form.validate_on_submit():
            request_paste = Pastes()
            if form.title.data:
                request_paste.title = form.title.data
            else:
                request_paste.title = "Untitled"

            request_paste.link = uuid.uuid4().hex
            request_paste.paste = form.paste.data
            request_paste.date = datetime.datetime.now()
            request_paste.date_timelive = getLifeTime(curr=request.form.get('date_timelive'))
            request_paste.private = form.is_private.data
            request_paste.user_id = current_user.id
            request_paste.code_id = request.form.get('code_id')
            db.session.add(request_paste)
            try:
                db.session.flush()
                db.session.commit()
            except:
                db.session.rollback()

            return redirect(url_for('Index.pastes', link=request_paste.link))

        return render_template('index.html', form=form, last_pasts=last_pasts())


class PostView(object):
    @staticmethod
    @IndexBlueprint.route('/pastes/<link>', methods=['GET', 'POST'])  # @такая же ебала как и в юзерах
    def pastes(link):
        timenow = datetime.datetime.now()
        try:
            paste = db.session.query(Pastes).filter(Pastes.link == link, Pastes.date_timelive > timenow).one()
            return render_template('pastes.html', paste=paste, last_pasts=last_pasts())

        except:
            return render_template('404.html'), 404


class MyPastesView(object):
    @staticmethod
    @IndexBlueprint.route('/mypastes/', methods=['GET', 'POST'])
    @login_required
    def my_pastes():
        form = PastesFormGet()
        query_args = []
        timenow = datetime.datetime.now()
        query_args.append("user_id = {0}".format(current_user.id))
        query_args.append("date_timelive > '{0}'".format(timenow))

        if request.args.get('code_id') and request.args.get('code_id') != '1':  # 1 - Selected Syntax: None
            query_args.append("code_id = {0}".format(request.args.get('code_id')))

        if request.args.get('title'):
            query_args.append("title = '{0}'".format(request.args.get('title')))

        if request.args.get('is_private'):
            query_args.append(
                "private = True")  # Является ли паста приватной

        try:
            query = db.session.query(Pastes) \
                .filter(*query_args) \
                .order_by(Pastes.id.desc()).limit(10)
            return render_template('mypastes.html', last_pasts=last_pasts(), my_pasts=query, form=form)
        except:
            query = db.session.query(Pastes) \
                .filter(Pastes.user_id == current_user.id) \
                .order_by(Pastes.id.desc()).limit(10)
            return render_template('mypastes.html', last_pasts=last_pasts(), my_pasts=query, form=form)

pastebin/templates/layout/footer.html
<footer>
    <div class="container">
        <p>&copy; 2017 502Paste. All Rights Reserved.</p>
    </div>
</footer>

pastebin/templates/layout/header.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{ url_for('Index.index') }}">502Paste</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="{{ url_for('Index.index') }}">Main</a>
                </li>

                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ url_for('User.user') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ url_for('Index.my_pastes') }}">My pastes</a>
                    </li>
                    {% if current_user.has_role('admin') %}
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" href="{{ url_for('admin.index') }}">Admin <i
                                    class="fa fa-cog" aria-hidden="true"></i></a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ url_for('security.logout') }}">Log Out <i
                                class="fa fa-sign-in" aria-hidden="true"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ url_for('security.register') }}">Register <i
                                class="fa fa-sign-in" aria-hidden="true"></i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" href="{{ url_for('security.login') }}">Log In <i
                                class="fa fa-sign-in" aria-hidden="true"></i></a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>