pastebin/forms/pastes.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SubmitField, SelectField
from wtforms.validators import DataRequired

from pastebin.models import db
from pastebin.models.models import Codelanguages
from datetime import timedelta, datetime
from enum import Enum


class LiveTime(Enum):
    N = (timedelta(days=+999999), 'Never')
    M10 = (timedelta(seconds=+600), '10 Minutes')
    H1 = (timedelta(seconds=+3600), '1 Hour')
    D1 = (timedelta(days=+1), '1 Day')
    W1 = (timedelta(days=+7), '1 Week')
    W2 = (timedelta(days=+14), '2 Weeks')
    M1 = (timedelta(days=+30), '1 Month')
    M6 = (timedelta(days=+180), '6 Months')
    Y1 = (timedelta(days=+365), '1 Year')


class PastesForm(FlaskForm):
    title = StringField('Title', render_kw={"placeholder": "Title"})
    is_private = BooleanField('Private')
    date_timelive = SelectField(
        'Paste Expiration',
        choices=[(i.name, i.value[1]) for i in LiveTime]  # Choises keys and description from LIVE TIME
    )
    paste = TextAreaField('', validators=[DataRequired()], render_kw={"placeholder": "Code"})
    code_id = SelectField('Code', coerce=int)
    submit = SubmitField('Submit')

    def __init__(self):
        super(PastesForm, self).__init__()
        query = Codelanguages.query.order_by(Codelanguages.id).all()
        ctx = [(s.id, s.name) for s in query]
        self.code_id.choices = ctx


class PastesFormGet(FlaskForm):
    title = StringField('Title', render_kw={"placeholder": "Title"})
    is_private = BooleanField('Private')
    code_id = SelectField('Code', coerce=int)
    submit = SubmitField('Search')

    def __init__(self):
        super(PastesFormGet, self).__init__()
        query = Codelanguages.query.order_by(Codelanguages.id).all()
        ctx = [(s.id, s.name) for s in query]
        self.code_id.choices = ctx


def getLifeTime(curr="N"):
    return datetime.now() + LiveTime[curr].value[0]

pastebin/controllers/users.py
import datetime
import os
import uuid
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from pastebin.controllers.index import last_pasts
from pastebin.forms.profile import EditProfileForm
from pastebin.models import db
from pastebin.models.models import User, Pastes
from pastebin.settings import Config

UserBlueprint = Blueprint('User', __name__, url_prefix='')


class UserView:
    @staticmethod
    @UserBlueprint.route('/user/', methods=['GET', 'POST'])
    @login_required
    def user():
        user = db.session.query(User).filter(User.id == current_user.id).first()
        timenow = datetime.datetime.now()
        my_pasts = db.session.query(Pastes) \
            .filter(Pastes.user_id == current_user.id, Pastes.date_timelive >= timenow) \
            .order_by(Pastes.id.desc()).limit(10)

        avatar = user.photo
        return render_template('user.html', user=user, last_pasts=last_pasts(), my_pasts=my_pasts)

    @staticmethod
    @UserBlueprint.route('/edit_profile/', methods=['GET', 'POST'])
    @login_required
    def edit_profile():
        update_data = {}

        form = EditProfileForm()
        if form.validate_on_submit():
            for key in form.data:
                if key == 'photo' and form.data[key]:
                    f = form.photo.data
                    filename = str(uuid.uuid4()) + '.' + f.filename.rsplit('.', 1)[1].lower()
                    f.save(os.path.join(Config.UPLOAD_FOLDER, filename))
                    update_data[key] = filename
                    continue
                elif form.data[key] != '' and key != 'submit' and key != 'photo':
                    update_data[key] = form.data[key]
            try:
                query = db.session.query(User) \
                    .filter(User.id == current_user.id) \
                    .update(update_data, synchronize_session='evaluate')
                db.session.flush()
                db.session.commit()
            except:
                pass

            return redirect(url_for('User.user'))

        return render_template('edit_profile.html', form=form)

pastebin/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>502Paste</title>
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Custom fonts for this template -->

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />

    <link href="{{ url_for('static', filename='css/new-age.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet">

    {% block page_css %}{% endblock %}

</head>


<body id="page-top">
{% include 'layout/header.html' %}

<section class="masthead">
    <div class="container h-100">
        <div class="row h-100">
            {% block body %} {% endblock %}
        </div>
    </div>
</section>

{% include 'layout/footer.html' %}

<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='js/new-age.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
<script>
    $('select').select2({width: '100%'})
</script>
{% block page_js %}{% endblock %}
</body>
</html>

pastebin/templates/edit_profile.html
{% extends "base.html" %}


{% block body %}
    <div class="col-lg-3"></div>
    <div class="col-lg-6 my-auto">
        {% block content %}
            <h1>Edit Profile</h1>
            {#    <a href="{{ url_for('security.change_password') }}">Zzazaza</a>#}
            <form action="" method="post" name="edit" class="send-form"  enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.name.label }}
                    {{ form.name(size = 24) }}
                </div>

                <div class="form-group">
                    {{ form.api_key.label }}
                    {{ form.api_key }}
                    <button class="generate_api">
                        generate
                    </button>
                </div>

                <div class="form-group">
                    {{ form.photo.label }}
                    {{ form.photo }}
                </div>

                <div class="form-group">
                    {{ form.submit(class="btn") }}
                </div>

            </form>
        {% endblock %}
    </div>
{% endblock %}

{% block page_js %}
    <script src="{{ url_for('static', filename="js/generate_api.js") }}"></script>
{% endblock %}

pastebin/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-lg-9 my-auto">
        <div class="header-content mx-auto">

            <h1>
                New Paste
            </h1>

            <form action="" method="post" class="send-form">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="">
                                Title:
                            </label>
                            {{ form.title }}
                        </div>
                        <div class="col-sm-6">
                            <label for="">
                                Syntax:
                            </label>
                            {{ form.code_id }}
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="">
                                Paste Expiration:
                            </label>
                            {{ form.date_timelive }}
                        </div>
                        <div class="col-sm-6">
                            <div class="form-checkbox">
                                <label for="private_msg" class="label-checkbox">Paste Exposure:</label>
                                {{ form.is_private }}
                            </div>
                        </div>
                    </div>
                </div>

                {{ form.paste(required=True) }}

                {{ form.submit(class="btn") }}
            </form>


        </div>
    </div>
    <div class="col-lg-3 my-auto">
        <div class="pastes">
            <h3>
                Public Pastes
            </h3>

            {% for item in last_pasts %}
                <a href="{{ url_for('Index.pastes', link=item.link) }}" class="paste">
                    <p class="paste_title">{{ item.title }}</p>
                    <span class="paste_date">{{ item.date.strftime('%H:%M:%S') }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

pastebin/templates/mypastes.html
{% extends 'base.html' %}

{% block body %}
    <div class="col-lg-9 my-auto">
        <div class="header-content mx-auto">

            <h1 class="mb-5">
                My pastes
            </h1>

            <form action="" method="get" class="send-form search-form">
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="">Title:</label>
                            {{ form.title(placeholder=request.args.get('title')) }}
                        </div>
                        <div class="col-md-4">
                            <label for="">Syntax:</label>
                            {{ form.code_id }}
                        </div>
                        <div class="col-md-4">
                            <div class="form-checkbox">
                                <label for="private_msg">Paste Exposure:</label>
                                {{ form.is_private() }}
                            </div>
                        </div>
                    </div>
                </div>

                {{ form.submit(class="btn") }}

            </form>

            {% for item in my_pasts %}
                <a href="{{ url_for('Index.pastes', link=item.link) }}" class="paste">
                    <p class="paste_title">{{ item.title }}</p>
                    <span class="paste_date">{{ item.date }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
    <div class="col-lg-3 my-auto">
        <div class="pastes">
            <h3>
                Public Pastes
            </h3>

            {% for item in last_pasts %}
                <a href="{{ url_for('Index.pastes', link=item.link) }}" class="paste">
                    <p class="paste_title">{{ item.title }}</p>
                    <span class="paste_date">{{ item.date.strftime('%H:%M:%S') }}</span>
                </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

pastebin/templates/pastes.html
{% extends 'base.html' %}

{% block page_css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/dracula.min.css">
{% endblock %}

{% block page_js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
    <script>
        $(document).ready(function () {
            hljs.initHighlightingOnLoad();
            $('pre code').each(function (i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>
{% endblock %}


{% block body %}
            <div class="col-lg-9 my-auto">
                <div class="header-content mx-auto">
                    <h1 class="mb-5">
                        {{ paste.title }}
                    </h1>

                    <pre><code>{{ paste.paste }}</code></pre>

                </div>
            </div>
            <div class="col-lg-3 my-auto">
                <div class="pastes">
                    <h3>
                        Public Pastes
                    </h3>
                    {% for item in last_pasts %}
                    <a href="{{ url_for('Index.pastes', link=item.link) }}" class="paste">
                        <p class="paste_title">{{ item.title }}</p>
                        <span class="paste_date">{{ item.date }}</span>
                    </a>
                    {% endfor %}
                </div>
            </div>
{% endblock %}

pastebin/templates/user.html
{% extends "base.html" %}

{% block body %}
    <div class="col-lg-2"></div>
    <div class="col-lg-8 my-auto">
        <div class="send-form clearfix">
            <div class="ava">
                <img src="{% if user.photo %}{{ url_for('static', filename='uploads/' + user.photo) }}{% else %}{{ user.gravatar(128) }}{% endif %}">
            </div>
            <div class="send-form_wrapper">
                {% if current_user.is_authenticated %}
                    <h3>
                        Name: <b>{{ user.name }}</b>
                        <small><a href="{{ url_for('User.edit_profile') }}">Edit</a></small>
                    </h3>
                {% endif %}
                <p>
                    Api Key: <b>{{ user.api_key }} </b>
                </p>
                <p>
                    <a href="{{ url_for('security.change_password') }}">Change password</a>
                </p>
                <hr>
                <h3>
                    Recent posts:
                </h3>
                {% for item in my_pasts %}
                    <a href="{{ url_for('Index.pastes', link=item.link) }}" class="paste">
                        <p class="paste_title">{{ item.title }}</p>
                        <span class="paste_date">{{ item.date.strftime('%H:%M:%S') }}</span>
                    </a>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}